src/main/java/com/apptastic/rssreader/RssReader.java

When the descirption is encapsulated within `CDATA`, then the description will be empty. Given the following RSS-feed, the description was empty before this fix:
```xml
<rss xmlns:media="http://search.yahoo.com/mrss/" version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"  xmlns:dc="http://purl.org/dc/elements/1.1/">
<channel>
<item>
<title>Am 5. Februar beginnt das Anmeldeverfahren...</title>
<link>https://www.....</link>
<description><![CDATA[<p class="bodytext">Die beiden städtischen Gesamtschulen führen ein vorgezogenes Anmeldeverfahren durch.</p>]]></description>
<pubDate>Mon, 27 Jan 2020 00:00:00 +0000</pubDate>
<guid>https://www......</guid>
</item>
```

Fix missing description for text within CDATA

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java

Trying to use addItemExtension() method for a tag with no namespace is not working.
Example:
Author will not be set to the value in name tag.
```java
List<Item> items = new RssReader()
.addItemExtension("name", Item::setAuthor)
.read("https://github.com/openjdk/jdk/commits.atom")
```
```xml
<entry>
<id>tag:github.com,2008:Grit::Commit/b35922be6de7b848a2982d6a278dbd205fc39e6a</id>
<link type="text/html" rel="alternate" href="https://github.com/openjdk/jdk/commit/b35922be6de7b848a2982d6a278dbd205fc39e6a"/>
<title>
8295714: GHA ::set-output is deprecated and will be removed
</title>
<updated>2022-10-21T08:23:45Z</updated>
<media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/u/6209108?s=30&amp;v=4"/>
<author>
<name>magicus</name> …
```

addItemExtension not working for tag with no namespace

---

src/main/java/com/apptasticsoftware/rssreader/DateTime.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/java/com/apptasticsoftware/rssreader/DateTimeTest.java

Unhandled timestamp format:
```
Wed, 09 Nov 2022 00:21:54 EDT
Wed, 09 Nov 2022 00:21:54 EST
Wed, 09 Nov 2022 00:21:54 CDT
Wed, 09 Nov 2022 00:21:54 CST
Wed, 09 Nov 2022 00:21:54 MDT
Wed, 09 Nov 2022 00:21:54 MST
Wed, 09 Nov 2022 00:21:54 PDT
Wed, 09 Nov 2022 00:21:54 PST
```

Timestamp format not recognized

---

src/main/java/com/apptasticsoftware/rssreader/DateTime.java
src/main/java/com/apptasticsoftware/rssreader/Item.java
src/main/java/com/apptasticsoftware/rssreader/util/ItemComparator.java
src/main/java/module-info.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/java/com/apptasticsoftware/integrationtest/SortTest.java

Changed sort order from oldest publication date first to newest publication date first when using `sort()` methods.
Added comparators for changing sort order.
Oldest publication date first:
```java
List<Item> items = new RssReader()
.read(URL)
.sorted(ItemComparator.oldestItemFirst())
```
Newest publication date first:
```java
List<Item> items = new RssReader()
.read(URL)
.sorted()  // default sort order 
//.sorted(ItemComparator.newestItemFirst())  // same as explicit sorting on newestItemFirst
```

Changed default sort order

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/main/java/com/apptasticsoftware/rssreader/Channel.java
src/main/java/com/apptasticsoftware/rssreader/Item.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/java/com/apptasticsoftware/rssreader/RssReaderTest.java
src/test/resources/multiple-categories.xml

Added getCategories() method in Channel and Item classes that returns a list of categories. 
```java
List<String> getCategories()
```
Deprecated method `String getCategory()`.

Support for more than one category

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/resources/bad-image-width-height.xml

Exception is thrown when parsing image with bad width or height value. Check if value is valid before converting string to integer/long.

Check if image width and height value is blank

---

src/main/java/com/apptasticsoftware/rssreader/DateTime.java
src/test/java/com/apptasticsoftware/rssreader/DateTimeTest.java

An exception is thrown when parsing timestamp with incorrect day-of-week.
Example:
Timestamp Tue, 23 May 2019 02:00:00 -0700. Day of week should be Thursday and no Tuesday.
Solution: Parse timestamp without day-of-week part if an exception is thrown due to incorrect day-of-week.

Exception when parsing timestamp with incorrect day of week

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java

#59 introduced a regression where calling `readAsync` (without calling `read` first) will cause all data to be empty/null.
This PR moves the `initialize` call to `readAsync`, because each function eventually calls into that anyway.
The only exception to this is the `read(InputStream)` overload, so it remains unchanged.

Fix RssReader not being initialized on readAsync calls

---

src/main/java/com/apptasticsoftware/rssreader/DateTime.java

Fixes issues with parsing timestamp "Sat, 21 Jan 2023 11:12:30 GMT" when system using German locale settings.
To reproduce use with JVM parameters `-Duser.country=DE -Duser.language=de`
Use `Locale.English` for all `DateTimeFormatter` instances.

Parse timestamps with locale English formatter

---

src/main/java/com/apptasticsoftware/rssreader/DateTime.java
src/test/java/com/apptasticsoftware/rssreader/DateTimeTest.java

Unhandled timestamp format (+5:30 offset used in India and Sri Lanka):
```
Fri, 03 Mar 2023 13:13:53+5:30
Fri, 03 Mar 2023 13:13:53-5:30
Fri, 03 Mar 2023 13:13:53+10:30
Fri, 03 Mar 2023 13:13:53-10:30
```

Unhandled datetime india format

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java

Fixes issue with `initialize()` being called in parallel when using `read(Collection<String> urls)` method.

Fix race condition for read(Collection<String> urls) calls

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/main/java/com/apptasticsoftware/rssreader/Channel.java
src/main/java/com/apptasticsoftware/rssreader/DateTime.java
src/main/java/com/apptasticsoftware/rssreader/DateTimeParser.java
src/main/java/com/apptasticsoftware/rssreader/Item.java
src/main/java/com/apptasticsoftware/rssreader/module/itunes/ItunesChannel.java
src/main/java/com/apptasticsoftware/rssreader/module/itunes/ItunesItem.java
src/main/java/com/apptasticsoftware/rssreader/module/itunes/ItunesRssReader.java
src/main/java/com/apptasticsoftware/rssreader/util/ItemComparator.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/java/com/apptasticsoftware/integrationtest/SortTest.java
src/test/java/com/apptasticsoftware/rssreader/RssReaderTest.java
src/test/java/com/apptasticsoftware/rssreader/module/itunes/ItunesRssReaderTest.java

Added `DateTimeParser` interface for parsing custom timestamp.
For parsing non-standard timestamp for example date format in Italy, `dom, 12 mar 2023 12:38:42 GMT`
Usage:
```java
DateTimeParser timestampParserItaly = (timestamp) -> {
var formatter = DateTimeFormatter.ofPattern("E, d MMM yyy HH:mm:ss z")
.withLocale(Locale.ITALY);
return ZonedDateTime.parse(timestamp, formatter);
};
var items = new RssReader().setDateTimeParser(timestampParserItaly)
.read(URL)
```

Support for custom timestamp parser

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java

For Atom feed `name` element can exist inside both `author` element and `contributor` element.  Allow to use full path expression`/feed/entry/author/name` and `/feed/entry/contributor/name` in extension to distinguish the two apart.
Atom feed example:
```xml
<feed>
...
<entry>
<title>An entry from my feed</title>
<summary>DEFAULT --- This is the default summary</summary>
<link rel="self" href="/web20/sample_atom_feed/entry" /> 
<author>
<name>Joe Bloggs</name>
<uri>http://www.hursley.ibm.com/JBloggs/</uri>
<email>JBloggs@uk.ibm.com</email>
</author>
<contributor>
<name>John Doe</name>
</contributor>
<category term="Comments" />
<published>2023-08-10T15:41:00</published>
</entry>
...
</feed>
```
Custom extension that maps value `Joe Bloggs` to field `Comments` in Item object using full …

Allow extension to use full path expression to a node in XML

---

src/main/java/com/apptasticsoftware/rssreader/DateTime.java
src/main/java/com/apptasticsoftware/rssreader/util/ItemComparator.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/java/com/apptasticsoftware/rssreader/DateTimeTest.java

Make it possible to change the default timezone to use if no timezone information exist in the timestamp string. Default UTC is used.
Example pubDate string `2023-08-11T07:17:52` is default treated as a UTC timestamp.
For changing the default timezone to `Australia/Sydney`:
```java
var items = new RssReader().setDateTimeParser(new DateTime("Australia/Sydney"))
.read(URL)
```

Make it possible to change the default timezone

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/resources/atom-feed.xml

Added missing mapping of Author field for Atom feed. Worked correctly for RSS feed.

Author field not mapped for Atom feed

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/resources/atom-feed.xml

For Atom feed if `content` or `summary` element contains XML then it is not mapped to `description` field.
Example:
```xml
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
<title>Example Feed</title>
<subtitle>A subtitle.</subtitle>
<link href="http://example.org/feed/" rel="self"/>
<link href="http://example.org/"/>
<updated>2003-12-13T18:30:02Z</updated>
<author>
<name>John Doe</name>
<email>johndoe@example.com</email>
</author>
<id>urn:uuid:60a76c80-d399-11d9-b91C-0003939e0af6</id>
<entry>
<content type="text/xml">
<p:Customer xmlns:p="http://www.ibm.com/crm" xmlns="http://www.ibm.com/crm">
<id>10</id>
</p:Customer>
</content>
<title>Atom-Powered Robots Run Amok</title>
<link href="http://example.org/2003/12/13/atom03"/> …
```

Content or summary element is not mapped if it contains XML

---

src/main/java/com/apptasticsoftware/rssreader/DateTime.java
src/test/java/com/apptasticsoftware/integrationtest/SortTest.java
src/test/java/com/apptasticsoftware/rssreader/DateTimeTest.java

Unhandled timestamp format:
`Saturday, 26 August 2023 21:00:00 +07:00`
This bug only affects code that calls `sort()` or calls getters that returns `ZonedDateTime`

Unhandled timestamp format

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/main/java/com/apptasticsoftware/rssreader/util/Mapper.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/java/com/apptasticsoftware/integrationtest/SortTest.java

Add default mapping for item tags.
`dc:creator` -> `Item:setAuthor`
`dc:date `-> `Item:setPubDate`
Mapping is only perform if `author` or `pubDate` tag is not present.

Add mapping for dc:creator and dc:date

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/main/java/com/apptasticsoftware/rssreader/Item.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/java/com/apptasticsoftware/rssreader/RssReaderTest.java
src/test/java/com/apptasticsoftware/rssreader/module/itunes/ItunesRssReaderTest.java
src/test/resources/multiple-enclosures.xml

Add support for multiple enclosures per RSS Item.
Method in Item class getting multiple enclosures:
```java
List<Enclosure> enclosures = item.getEnclosures();
```

Support for multiple enclosures

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java

This PR skips leading whitespaces when reading feed.

Fails to parse feed that start with whitespace

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/resources/multiple-categories.xml
src/test/resources/multiple-title-on-different-levels.xml

If title or description tag exist on multiple levels the value of the last occurrence will be selected.
For rss feeds description tag can exist in:
`/rss/channel/description` and `/rss/channel/image/description`
For atom feeds title tag can exist in:
`/feed/entry/title` and `/feed/entry/source/title`
Use absolute path to title and description tags instead of relative path with setting up the item and channel mappings.

Wrong title and description could be selected

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/resources/rdf-feed.xml

Added dc mappings to existing RSS fields (if field is not mapped with a value before):
dc:language -> channel::getLanguage
dc:publisher -> channel::getCopyright
dc:title -> channel::getTitle
dc:identifier -> item::getGuid
dc:title -> item::getTitle

Add dc mappings

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/resources/atom-feed-category.xml

Added category mapping for Atom feed.
/feed/category[term] -> Channel::getCategories)
/feed/entry/category[term] -> Item::getCategories)
```xml
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
...
<category term="Computer"/>
<category term="Developer"/>
...
<entry>
...
<category term="Microsoft"/>
<category term="API"/>
<category term="Azure"/>
...
</entry>
</feed>
```

Atom category mappings

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/test/java/com/apptasticsoftware/integrationtest/ConnectionTest.java
src/test/java/com/apptasticsoftware/rssreader/util/RssServer.java

Added timeout for reading the response body. Default value for read timeout is 25 seconds.
Also exposed methods for setting connection timeout and request timeout. The default value for these timeouts are 25 seconds same as in previous releases.
Example for changing timeout:
```java
var timeout = Duration.ofSeconds(10);
var items = new RssReader()
.setConnectionTimeout(timeout)
.setRequestTimeout(timeout)
.setReadTimeout(timeout)
.read("https://lwn.net/headlines/rss")
```
This PR fixes issue #163

Add read timeout

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/main/java/com/apptasticsoftware/rssreader/util/DaemonThreadFactory.java

The PR fixes an issue causing the program never to stop.
Example:
```java
public static void main(String[] args) throws IOException {
RssReader rssReader = new RssReader();
List<Item> items = rssReader.read(URL).toList();
}
```
Fixed by using daemon threads in the executor service

RSS reader never stops

---

.github/workflows/pr-agent.yml
src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/main/java/com/apptasticsoftware/rssreader/util/Mapper.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/java/com/apptasticsoftware/integrationtest/SortTest.java

enhancement
___
- Replaced `LOG_GROUP` with `LOGGER` for consistent logging across the codebase.
- Improved code readability and maintainability by making several methods private and adding braces to single-line if statements.
- Removed unnecessary blank lines to streamline the code.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>AbstractRssReader.java</strong><dd><code>Refactor logging and method visibility in AbstractRssReader</code></dd></summary>
<hr>
src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
<li>Replaced <code>LOG_GROUP</code> with <code>LOGGER</code> for logging.<br> <li> Made several methods private for encapsulation.<br> <li> …

Refactoring

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/main/java/com/apptasticsoftware/rssreader/internal/StreamUtil.java
src/main/java/com/apptasticsoftware/rssreader/internal/stream/AbstractAutoCloseStream.java
src/main/java/com/apptasticsoftware/rssreader/internal/stream/AutoCloseDoubleStream.java
src/main/java/com/apptasticsoftware/rssreader/internal/stream/AutoCloseIntStream.java
src/main/java/com/apptasticsoftware/rssreader/internal/stream/AutoCloseLongStream.java
src/main/java/com/apptasticsoftware/rssreader/internal/stream/AutoCloseStream.java
src/test/java/com/apptasticsoftware/integrationtest/CloseTest.java
src/test/java/com/apptasticsoftware/integrationtest/ConnectionTest.java
src/test/java/com/apptasticsoftware/integrationtest/SortTest.java
src/test/java/com/apptasticsoftware/rssreader/internal/RssServer.java
src/test/resources/rss-feed.xml

This PR fixes some cases where the underlying resources are not closed properly.
If you use the `iterator()` or `spliterator()` methods, the underlying resources will not close automatically.
___
Enhancement, Tests
___
- Introduced `AutoCloseStream` and related classes to manage stream resources automatically, ensuring proper closure and resource management.
- Added `StreamUtil` class to facilitate stream operations, such as creating a stream from an iterator.
- Implemented comprehensive tests in `CloseTest` to verify the automatic closure of streams and resource management.
- Refactored existing tests to improve readability and maintainability, including updates to import paths and stream operations.
___
<table><thead><tr><th></th><th align="left">Relevant …

Close underlying resources

---

.github/workflows/codeql-analysis.yml
build.gradle
src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/java/com/apptasticsoftware/rssreader/RssReaderTest.java

This PR fixes a special case where the underlying resource was not closed when using zero read timeout and reading the feed using an iterator or a spliterator.
Example:
```java
var stream = new RssReader().setReadTimeout(Duration.ZERO).read(URL);
var iterator = stream.iterator();
var item = iterator.next();
```
___
Bug fix, Enhancement, Tests
___
- Implemented a `Cleaner` in `AbstractRssReader` to ensure underlying resources are properly closed when no timeout is used.
- Added a new `CleaningAction` class to handle the closing of `XMLStreamReader` and other resources.
- Modified `RssItemIterator` to implement `AutoCloseable` and utilize `Cleaner` for resource management.
- Enhanced the integration tests to include a test case for verifying resource cleanup using `Cleaner`.
- Updated …

Close underlying resources when no timeout is used

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/java/com/apptasticsoftware/integrationtest/SortTest.java

Added support for reading from file URI.
Example reading from a single file:
```java
List<Item> items = new RssReader().read("file:/path/to/file").toList()
```
Example reading from a mix of files and URLs:
```java
List<String> sources = List.of(
"file:/path/to/file",
"https://www.nasa.gov/news-release/feed/",
"file:///path/to/another/file",
"https://www.engadget.com/rss.xml"));
List<Item> items = new RssReader().read(sources).toList()
```

Support for reading from file URI

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java

This PR enables the read method to accept and process RSS/Atom feed data provided as a string.
Example:
```java
String feed = "<rss>...</rss>"
List<Item> items = new RssReader().read(feed).toList()
```

Parse a feed from a string

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/main/java/com/apptasticsoftware/rssreader/Item.java
src/test/java/com/apptasticsoftware/integrationtest/RssReaderIntegrationTest.java
src/test/java/com/apptasticsoftware/rssreader/RssReaderTest.java

Add new content field to Item class.
Add feed mappings:
`/feed/entry/content` -> Item::getContent
`content:encoded` -> Item::getContent

Add content field to item

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/main/java/com/apptasticsoftware/rssreader/Item.java
src/main/java/com/apptasticsoftware/rssreader/util/ItemComparator.java
src/test/java/com/apptasticsoftware/rssreader/util/ItemComparatorTest.java

Added comparators for sorting items by updated time.
* `ItemComparator::oldestUpdatedItemFirst`
* `ItemComparator::newestUpdatedItemFirst`
Renamed comparators for sorting by published time.
* `ItemComparator::oldestItemFirst` -> `ItemComparator::oldestPublishedItemFirst`
* `ItemComparator::newestItemFirst `-> `ItemComparator::newestPublishedItemFirst`
Deprecated old method names and marked them for removal in future versions.

Comparators for sorting items by updated time

---

src/main/java/com/apptasticsoftware/rssreader/AbstractRssReader.java
src/test/java/com/apptasticsoftware/rssreader/RssReaderTest.java

Improve log message by including the feed URL / file path when an exception is caught.
Example log message:
```java
WARNING: Failed to parse XML from feed https://capitallinkshipping.com/login/?redirect_to=https%3A%2F%2Fcapitallinkshipping.com%2Ffeed%2F
javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,3]
Message: The markup in the document preceding the root element must be well-formed.
at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
at com.apptasticsoftware.rssreader.AbstractRssReader$RssItemIterator.next(AbstractRssReader.java:698)
at com.apptasticsoftware.rssreader.AbstractRssReader$RssItemIterator.peekNext(AbstractRssReader.java:674)
at com.apptasticsoftware.rssreader.AbstractRssReader$RssItemIterator.hasNext(Abs …
```

Improve log message

---

build.gradle

This PR fixes issue #218
Added the following attributes to MANIFEST.MD file.
```
Manifest-Version: 1.0
Automatic-Module-Name: com.apptasticsoftware.rssreader
Bnd-LastModified: 1745170840738
Build-Jdk-Spec: 11
Bundle-Description: Java library for reading RSS and Atom feeds
Bundle-License: https://opensource.org/licenses/MIT
Bundle-ManifestVersion: 2
Bundle-Name: RSS Reader
Bundle-SymbolicName: com.apptasticsoftware.rssreader
Bundle-Version: 3.9.3
Created-By: 21.0.1 (Eclipse Adoptium)
Export-Package: com.apptasticsoftware.rssreader;version="3.9.3",com.ap
ptasticsoftware.rssreader.internal;uses:="javax.xml.stream";version="
3.9.3",com.apptasticsoftware.rssreader.internal.stream;version="3.9.3
",com.apptasticsoftware.rssreader.module.itunes;uses:="com.apptastics …
```

Add jar manifest attributes
